"""Detection of WAF / bot-mitigation block responses, and the back-off-then-stop
policy for reacting to them.

Two concerns, kept separate and independently testable:

- detect_block(): given a page's status, title and a slice of its HTML, decide
  whether this looks like a block/challenge page. Many WAFs (notably F5 BIG-IP
  ASM) serve the block as HTTP 200, so content signatures are primary and status
  codes are a secondary signal.

- BlockController: a per-seed state machine. On the first block it asks the
  caller to back off (cool down + slow the crawl); if blocks persist it asks the
  caller to stop the seed, on the assumption the rest of the site will behave the
  same. A single successful page resets it.
"""

from __future__ import annotations

from dataclasses import dataclass

from .config import BehaviorConfig

# High-precision phrases: specific enough that appearing in ordinary page copy
# is very unlikely. Matched case-insensitively against title + a body slice.
BLOCK_SIGNATURES = [
    "the requested url was rejected",        # F5 BIG-IP ASM / Advanced WAF
    "your support id is",                    # F5 BIG-IP ASM
    "request unsuccessful. incapsula",       # Imperva Incapsula
    "incapsula incident id",                 # Imperva Incapsula
    "attention required! | cloudflare",      # Cloudflare challenge
    "checking your browser before accessing",# Cloudflare I'm-Under-Attack
    "cf-error-details",                      # Cloudflare error page marker
    "pardon our interruption",               # HUMAN / PerimeterX
    "please verify you are a human",         # generic bot check
    "please enable javascript and cookies",  # Cloudflare/managed challenge
    "you have been blocked",                 # Cloudflare / Wordfence
    "access to this page has been denied",   # PerimeterX
    "reference #",                           # Akamai (paired with edgesuite below)
    "errors.edgesuite.net",                  # Akamai reference error page
    "generated by cloudfront",               # AWS CloudFront/WAF deny
    "this request was blocked by",           # generic WAF wording
]

# Status codes that indicate refusal / rate-limiting on their own.
BLOCK_STATUS = {403, 429, 503}


def detect_block(status: int | None, title: str | None,
                 body_snippet: str | None) -> tuple[bool, str | None]:
    """Return (blocked, reason)."""
    hay = ((title or "") + "\n" + (body_snippet or "")).lower()
    for sig in BLOCK_SIGNATURES:
        if sig in hay:
            return True, f"signature:{sig!r}"
    if status in BLOCK_STATUS:
        return True, f"http:{status}"
    return False, None


@dataclass
class BlockDecision:
    action: str            # "proceed" | "backoff" | "stop"
    consecutive: int = 0
    cooldown: float = 0.0
    delay_multiplier: float = 1.0
    recovered: bool = False


class BlockController:
    """Per-seed back-off/stop state machine driven by block detections."""

    def __init__(self, cfg: BehaviorConfig):
        self.cfg = cfg
        self.consecutive = 0
        self.delay_multiplier = 1.0

    def record(self, blocked: bool) -> BlockDecision:
        if not blocked:
            recovered = self.consecutive > 0
            self.consecutive = 0
            self.delay_multiplier = 1.0
            return BlockDecision("proceed", consecutive=0,
                                 delay_multiplier=1.0, recovered=recovered)

        self.consecutive += 1
        # Persistent block: give up on this seed. The rest of the site is very
        # likely gated the same way, so continuing only antagonises the WAF.
        if self.consecutive >= self.cfg.block_max_consecutive:
            return BlockDecision("stop", consecutive=self.consecutive)

        # First (and subsequent, up to the limit) block: slow right down and
        # cool off before trying the next page.
        self.delay_multiplier *= self.cfg.block_backoff_factor
        cooldown = self.cfg.block_cooldown * self.consecutive
        return BlockDecision("backoff", consecutive=self.consecutive,
                             cooldown=cooldown,
                             delay_multiplier=self.delay_multiplier)
