"""X (formerly Twitter) capture for SWM.

X is captured as a preservation package, in the same order of primacy as
Instagram's:

1. media as X served it -- the ``orig`` rendition of each image, the
   highest-bitrate progressive MP4 of each video -- with SHA-256 fixity;
2. the untouched responses X returned, under ``raw/``;
3. normalised posts and users as JSONL/CSV;
4. optionally, a WARC of every exchange the browser made, for how X
   presented what was collected;
5. a manifest stating what was asked for, what was reached, what failed and
   what was not attempted.

Collection happens through the browser X serves: a real Chrome, signed in
once by the curator in a dedicated profile, opening a profile, a post or a
search the way a person does. X's own web client builds every request; SWM
recognises the operation from the request's URL and reads the answer. That
sidesteps the three things every reader that builds its own requests spends
its life chasing (rotating operation ids, drifting feature flags, and a
transaction header generated by an obfuscated script), and leaves X's
rate limits and account checks as the conditions they are.

The engine here is written against a client protocol so the collector
(``x_browser``) can be exercised with a stand-in. Framework pieces --
holds, rate-limit waits, checkpoints, the manifest conventions, the
metadata layer -- follow the Instagram mode; the records are X's own:
replies are posts, reposts are kept with the original inside and never
shown as the account's authorship, quotes carry the quoted post, and
other people's posts pulled in to explain a conversation are marked as
context and never counted as the account's.
"""
from __future__ import annotations

import csv
import hashlib
import json
import logging
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Callable, Iterable, Iterator, Optional, Protocol
from urllib.parse import parse_qs, quote, unquote, urlsplit

from .facebook import (_append_jsonl, _atomic_json, _date_bound, _iso_now,
                       _media_suffix)
from .redaction import redact_body
from .x_extract import XAbsence, XMediaItem, XPost, XUser

log = logging.getLogger(__name__)

RECORDING = "recording"
PAUSED = "paused"
BLOCKED = "blocked"
STOPPED = "stopped"

CMD_PAUSE = "pause"
CMD_RESUME = "resume"
CMD_STOP = "stop"

X_MODES = {"date_range", "latest_n", "until_stopped", "end_of_timeline", "since_last"}
X_SURFACES = ("posts", "replies", "media")
SEARCH_PRODUCTS = ("Latest", "Top")

# X pins one post; a stopping rule that needs more than one consecutive
# older post cannot be tripped by it, recognised or not.
_MAX_PINNED = 1


# ---------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------

_X_HOSTS = {"x.com", "www.x.com", "mobile.x.com", "twitter.com",
            "www.twitter.com", "mobile.twitter.com"}
_HANDLE_RE = re.compile(r"^[A-Za-z0-9_]{1,15}$")
_RESERVED = {
    "home", "explore", "notifications", "messages", "i", "settings", "search",
    "hashtag", "login", "logout", "compose", "intent", "share", "account",
    "tos", "privacy", "about", "jobs", "signup", "flow", "communities",
    "lists", "bookmarks", "premium", "verified-choose",
}


@dataclass(frozen=True)
class XTarget:
    """What a curator asked for, once the text has been read."""
    kind: str                      # "profile" | "post" | "search"
    handle: Optional[str] = None
    post_id: Optional[str] = None
    query: Optional[str] = None
    product: str = "Latest"
    url: str = ""

    @property
    def key(self) -> str:
        if self.kind == "profile":
            return f"x:@{(self.handle or '').lower()}"
        if self.kind == "post":
            return f"x:/{self.post_id}"
        return f"x:search:{self.product.lower()}:{(self.query or '').strip().lower()}"

    @property
    def label(self) -> str:
        if self.kind == "profile":
            return f"@{self.handle}"
        if self.kind == "post":
            return f"post {self.post_id}"
        return f"search \u201c{self.query}\u201d ({self.product})"


def search_url(query: str, product: str = "Latest") -> str:
    tab = {"latest": "live", "top": "top", "media": "media"}.get(product.lower(), "live")
    return f"https://x.com/search?q={quote(query, safe='')}&src=typed_query&f={tab}"


def parse_x_target(raw: object, product: str = "Latest") -> XTarget:
    """Read a handle, a profile URL, a post URL, a hashtag or a search.

    Accepted: ``@handle`` or ``handle``; ``https://x.com/handle`` (with or
    without ``/with_replies`` or ``/media``); ``https://x.com/handle/status/
    <id>``; ``#tag`` or ``https://x.com/hashtag/tag``; ``search:<query>`` or
    a ``https://x.com/search?q=`` URL. twitter.com addresses are read as
    x.com ones. Home, notifications, messages and the rest of the signed-in
    client's own pages are refused: they are the viewer's, not a target.
    """
    text = str(raw or "").strip()
    if not text:
        raise ValueError("Enter an X handle, profile, post, hashtag or search.")
    product = product if product in SEARCH_PRODUCTS else "Latest"
    lowered = text.lower()
    if lowered.startswith("search:"):
        query = text[len("search:"):].strip()
        if not query:
            raise ValueError("A search needs some words after \u201csearch:\u201d.")
        return XTarget("search", query=query, product=product,
                       url=search_url(query, product))
    if text.startswith("#") and "/" not in text and " " not in text:
        tag = text[1:]
        if not re.match(r"^[\w]{1,100}$", tag):
            raise ValueError(f"{text!r} is not a hashtag.")
        return XTarget("search", query=f"#{tag}", product=product,
                       url=search_url(f"#{tag}", product))
    if "://" not in text and "/" not in text and "?" not in text:
        handle = text.lstrip("@")
        if not _HANDLE_RE.match(handle):
            raise ValueError(f"{text!r} is not an X handle: up to 15 letters, "
                             "digits or underscores.")
        if handle.lower() in _RESERVED:
            raise ValueError(f"{handle!r} is one of X's own pages, not an account.")
        return XTarget("profile", handle=handle, url=f"https://x.com/{handle}")
    if "://" not in text:
        text = "https://" + text
    parts = urlsplit(text)
    host = (parts.hostname or "").lower()
    if host not in _X_HOSTS:
        raise ValueError(f"{text} is not an X (or twitter.com) address.")
    segments = [s for s in (parts.path or "/").split("/") if s]
    if not segments:
        raise ValueError("Enter a profile, post, hashtag or search address, "
                         "not X's home page.")
    head = segments[0].lower()
    if head == "search":
        params = parse_qs(parts.query)
        query = (params.get("q") or [""])[0].strip()
        if not query:
            raise ValueError("The search address carries no query (q=).")
        tab = (params.get("f") or ["live"])[0].lower()
        chosen = {"live": "Latest", "top": "Top"}.get(tab, product)
        return XTarget("search", query=query, product=chosen,
                       url=search_url(query, chosen))
    if head == "hashtag" and len(segments) >= 2:
        tag = unquote(segments[1])
        return XTarget("search", query=f"#{tag}", product=product,
                       url=search_url(f"#{tag}", product))
    if head == "i" and len(segments) >= 3 and segments[1] in ("status", "web"):
        post_id = segments[2]
        if not post_id.isdigit():
            raise ValueError(f"{post_id!r} is not a post id.")
        return XTarget("post", post_id=post_id, url=f"https://x.com/i/status/{post_id}")
    if head in _RESERVED:
        raise ValueError(
            f"/{segments[0]}/ is one of X's own pages -- the viewer's home, "
            "notifications, messages or settings -- not an account, a post "
            "or a search.")
    handle = segments[0]
    if not _HANDLE_RE.match(handle):
        raise ValueError(f"{handle!r} is not an X handle.")
    if len(segments) >= 3 and segments[1] == "status":
        post_id = segments[2]
        if not post_id.isdigit():
            raise ValueError(f"{post_id!r} is not a post id.")
        return XTarget("post", handle=handle, post_id=post_id,
                       url=f"https://x.com/{handle}/status/{post_id}")
    if len(segments) > 2 or (len(segments) == 2 and segments[1] not in (
            "with_replies", "media", "highlights", "likes", "articles")):
        raise ValueError(f"/{'/'.join(segments)} is not a profile, post, "
                         "hashtag or search address.")
    return XTarget("profile", handle=handle, url=f"https://x.com/{handle}")


# ---------------------------------------------------------------------------
# The client the engine talks to
# ---------------------------------------------------------------------------

class XError(Exception):
    """Base for the conditions the engine has a response to."""


class RateLimited(XError):
    def __init__(self, wait_seconds: float = 300.0, detail: str = ""):
        super().__init__(detail or "X is limiting requests.")
        self.wait_seconds = wait_seconds


class LoginRequired(XError):
    """The session is missing, expired, or not enough for this target."""


class CheckpointRequired(XError):
    """X wants a person: a verification, a lock, a challenge."""


class TargetUnavailable(XError):
    """Not found, suspended, protected and not followed, or not servable."""


class XClient(Protocol):
    """What the engine needs from X, so a test can stand it in.

    Every method returns plain records carrying the untouched payload in
    ``raw``; the client does not decide what to keep.
    """

    def viewer(self) -> Optional[str]: ...
    def user(self, handle: str) -> XUser: ...
    def timeline(self, user: XUser, surface: str) -> Iterator[XPost]: ...
    def post(self, post_id: str) -> XPost: ...
    def conversation(self, post_id: str) -> Iterator[XPost]: ...
    def search(self, query: str, product: str) -> Iterator[XPost]: ...
    def fetch(self, url: str) -> tuple[bytes, str]: ...


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def _whole(value: object, default: int, label: str, low: int, high: int) -> int:
    if value in (None, ""):
        return default
    try:
        number = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{label} must be a whole number.") from exc
    if not low <= number <= high:
        raise ValueError(f"{label} must be between {low:,} and {high:,}.")
    return number


@dataclass
class XCaptureConfig:
    targets: list[str]
    mode: str = "latest_n"
    requested_mode: Optional[str] = None
    from_date: Optional[str] = None
    to_date: Optional[str] = None
    latest_n: int = 100
    consecutive_older: int = 5
    surfaces: tuple[str, ...] = ("posts",)
    search_product: str = "Latest"
    capture_media: bool = True
    keep_reposts: bool = True
    include_conversation: bool = False
    max_replies_per_post: int = 50
    write_warc: bool = False
    end_stall_rounds: int = 3
    prior_newest: dict = field(default_factory=dict)   # key -> {post_id, date}
    continuation_of: Optional[int] = None
    operator: str = "webarc"
    browser_profile_dir: Optional[str] = None
    browser_mode: str = "headed"
    chrome_path: Optional[str] = None

    @classmethod
    def from_dict(cls, raw: dict) -> "XCaptureConfig":
        targets_raw = raw.get("targets")
        if isinstance(targets_raw, str):
            targets_raw = [line for line in re.split(r"[\n,]+", targets_raw)
                           if line.strip()]
        if not isinstance(targets_raw, list) or not targets_raw:
            raise ValueError("Add at least one X handle, profile, post, hashtag or search.")
        product = str(raw.get("search_product") or "Latest")
        if product not in SEARCH_PRODUCTS:
            raise ValueError("search_product must be 'Latest' or 'Top'")
        targets: list[str] = []
        for item in targets_raw:
            target = parse_x_target(item, product)
            if target.url not in targets:
                targets.append(target.url)
        mode = str(raw.get("mode") or "latest_n")
        if mode not in X_MODES:
            raise ValueError(f"Unsupported X capture mode: {mode}")
        browser_mode = str((raw.get("browser") or {}).get("mode")
                           or raw.get("browser_mode") or "headed")
        if browser_mode not in ("headed", "native"):
            raise ValueError("browser must be 'headed' or 'native'")
        from_date = _date_bound(raw.get("from_date"))
        to_date = _date_bound(raw.get("to_date"), end=True)
        if from_date and to_date and from_date > to_date:
            raise ValueError("The From date must be on or before the To date.")
        if mode == "date_range" and not from_date:
            raise ValueError("Date range mode requires a From date.")
        surfaces_raw = raw.get("surfaces") or ["posts"]
        if isinstance(surfaces_raw, str):
            surfaces_raw = [surfaces_raw]
        surfaces = tuple(s for s in X_SURFACES if s in surfaces_raw)
        if not surfaces:
            raise ValueError("Select at least one of Posts, Replies and Media.")
        prior = raw.get("prior_newest") or {}
        if mode == "since_last":
            missing = [u for u in targets
                       if parse_x_target(u, product).kind != "post"
                       and not (prior.get(parse_x_target(u, product).key) or {}).get("post_id")]
            if missing:
                raise ValueError(
                    "No previous capture state exists for "
                    + ", ".join(parse_x_target(u, product).label for u in missing)
                    + ". Run another capture mode first.")
        return cls(
            targets=targets, mode=mode, requested_mode=mode,
            from_date=from_date, to_date=to_date,
            latest_n=_whole(raw.get("latest_n"), 100, "Latest N", 1, 100_000),
            consecutive_older=max(_MAX_PINNED + 1, _whole(
                raw.get("consecutive_older"), 5, "Consecutive older posts", 2, 25)),
            surfaces=surfaces, search_product=product,
            capture_media=bool(raw.get("capture_media", True)),
            keep_reposts=bool(raw.get("keep_reposts", True)),
            include_conversation=bool(raw.get("include_conversation", False)),
            max_replies_per_post=_whole(
                raw.get("max_replies_per_post"), 50, "Maximum replies per post", 1, 5_000),
            write_warc=bool(raw.get("write_warc", False)),
            end_stall_rounds=max(1, _whole(
                raw.get("end_stall_rounds"), 3, "Stall rounds", 1, 20)),
            prior_newest=dict(prior),
            continuation_of=raw.get("continuation_of"),
            operator=str(raw.get("operator") or "webarc"),
            browser_profile_dir=(raw.get("browser_profile_dir")
                                 or (raw.get("browser") or {}).get("user_data_dir")),
            browser_mode=browser_mode,
            chrome_path=(raw.get("browser") or {}).get("chrome_path"),
        )


# ---------------------------------------------------------------------------
# Archive: everything written to disk
# ---------------------------------------------------------------------------

class XArchive:
    """The capture package on disk, written incrementally.

    Responses go under ``raw/responses/`` verbatim (session material
    removed), the extracted node for each post and user beside them. Media
    is content-addressed so a file referenced by several posts is kept
    once. Exports are appended as records arrive, so an interrupted run
    leaves a readable package.
    """

    POST_FIELDS = [
        "post_id", "author_id", "author_handle", "author_name", "relationship",
        "capture_role", "text", "created_time", "conversation_id",
        "in_reply_to_post_id", "in_reply_to_handle", "permalink_url", "lang",
        "reply_count", "repost_count", "like_count", "quote_count",
        "bookmark_count", "view_count", "media_urls", "media_files", "is_pinned",
        "original_post_id", "original_author_handle", "quoted_post_id",
        "quoted_author_handle", "surface", "source", "target_key",
    ]

    def __init__(self, out_dir: Path):
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.raw_dir = self.out_dir / "raw"
        self.responses_dir = self.raw_dir / "responses"
        self.media_dir = self.out_dir / "media"
        self.posts_path = self.out_dir / "x-posts.jsonl"
        self.users_path = self.out_dir / "x-users.json"
        self.media_path = self.out_dir / "x-media.json"
        self.events_path = self.out_dir / "x-events.jsonl"
        self.manifest_path = self.out_dir / "x-manifest.json"
        self.checkpoint_path = self.out_dir / "x-checkpoint.json"
        self.checksums_path = self.out_dir / "checksums.sha256"
        self.posts: dict[str, XPost | dict] = {}
        self.users: dict[str, XUser] = {}
        self.media_index: dict[str, dict] = {}
        self._checksums: dict[str, str] = {}
        self.responses_saved = 0
        self._response_serial = self._next_response_serial()
        self._load_existing()

    def _next_response_serial(self) -> int:
        highest = 0
        if self.responses_dir.is_dir():
            for existing in self.responses_dir.glob("response-*.json"):
                digits = existing.stem.rsplit("-", 1)[-1]
                if digits.isdigit():
                    highest = max(highest, int(digits))
        return highest + 1

    def _load_existing(self) -> None:
        if self.media_path.exists():
            try:
                loaded = json.loads(self.media_path.read_text(encoding="utf-8"))
                if isinstance(loaded, dict):
                    self.media_index = {k: v for k, v in loaded.items() if isinstance(v, dict)}
            except (OSError, json.JSONDecodeError):
                pass
        if self.posts_path.exists():
            with self.posts_path.open(encoding="utf-8") as handle:
                for line in handle:
                    try:
                        row = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if isinstance(row, dict) and row.get("post_id"):
                        self.posts[str(row["post_id"])] = row

    # -- events -------------------------------------------------------------
    def event(self, event: str, **details: object) -> None:
        _append_jsonl(self.events_path, {"time": _iso_now(), "event": event, **details})

    # -- raw ----------------------------------------------------------------
    def save_raw(self, kind: str, name: str, payload: object) -> Path:
        target = self.raw_dir / kind / f"{_safe_name(name)}.json"
        target.parent.mkdir(parents=True, exist_ok=True)
        _atomic_json(target, payload)
        self._checksum(target)
        return target

    def save_response(self, meta: dict, body: bytes) -> str:
        """Keep a response exactly as received; returns its package path."""
        name = f"response-{self._response_serial:06d}.json"
        self._response_serial += 1
        target = self.responses_dir / name
        target.parent.mkdir(parents=True, exist_ok=True)
        safe_body, redacted = redact_body(body, str(meta.get("content_type") or ""))
        _atomic_json(target, {
            **meta, "body_bytes": len(safe_body),
            "body_sha256": hashlib.sha256(safe_body).hexdigest(),
            "redacted_fields": redacted,
            "body": safe_body.decode("utf-8", errors="replace")})
        self._checksum(target)
        self.responses_saved += 1
        return f"raw/responses/{name}"

    # -- records ------------------------------------------------------------
    def add_user(self, user: XUser) -> None:
        self.users[user.user_id] = user
        _atomic_json(self.users_path, {
            uid: _without_raw(asdict(u)) for uid, u in self.users.items()})
        self.save_raw("users", user.handle, user.raw)

    def add_post(self, post: XPost) -> bool:
        current = self.posts.get(post.post_id)
        if current is not None:
            # a post first seen as context and now selected as the target's
            # is the target's; the reverse never demotes
            role = current.capture_role if isinstance(current, XPost) else current.get("capture_role")
            if role == "conversation_context" and post.capture_role == "target":
                self.posts[post.post_id] = post
                if post.raw:
                    self.save_raw("posts", post.post_id, post.raw)
                return True
            return False
        self.posts[post.post_id] = post
        _append_jsonl(self.posts_path, self._post_row(post))
        if post.raw:
            self.save_raw("posts", post.post_id, post.raw)
        return True

    def _post_row(self, post: "XPost | dict") -> dict:
        if isinstance(post, dict):
            return dict(post)
        row = _without_raw(asdict(post))
        row.pop("media", None)
        urls = [m.url for m in post.media]
        row["media_urls"] = urls
        row["media_files"] = [(self.media_index.get(u) or {}).get("file") for u in urls]
        original = post.original_post or {}
        quoted = post.quoted_post or {}
        row["original_post_id"] = original.get("post_id")
        row["original_author_handle"] = original.get("author_handle")
        row["quoted_post_id"] = quoted.get("post_id")
        row["quoted_author_handle"] = quoted.get("author_handle")
        for embedded in (original, quoted):
            for item in embedded.get("media") or []:
                if isinstance(item, dict) and item.get("url"):
                    item["file"] = (self.media_index.get(item["url"]) or {}).get("file")
        row.setdefault("target_key", post.provenance.get("target_key"))
        return row

    # -- media --------------------------------------------------------------
    def save_media(self, url: str, body: bytes, content_type: str = "", *,
                   discovered_from: Optional[str] = None,
                   page_loaded_variant: Optional[str] = None,
                   requested_variant: Optional[str] = None,
                   fetched_url: Optional[str] = None,
                   fetched_via: Optional[str] = None) -> dict:
        existing = self.media_index.get(url)
        if existing:
            return existing
        digest = hashlib.sha256(body).hexdigest()
        name = f"{digest}{_media_suffix(fetched_url or url, content_type)}"
        self.media_dir.mkdir(parents=True, exist_ok=True)
        target = self.media_dir / name
        if not target.exists():
            temporary = target.with_name(name + ".tmp")
            temporary.write_bytes(body)
            temporary.replace(target)
        entry = {"file": name, "sha256": digest, "bytes": len(body),
                 "content_type": content_type or None,
                 "discovered_from": discovered_from,
                 "page_loaded_variant": page_loaded_variant,
                 "requested_variant": requested_variant,
                 "fetched_url": fetched_url or url,
                 "fetch_initiator": "swm",
                 "fetched_via": fetched_via,
                 "browser_fallback": fetched_via == "playwright-api-request"}
        self.media_index[url] = entry
        self._checksums[f"media/{name}"] = digest
        return entry

    # -- fixity -------------------------------------------------------------
    def _checksum(self, path: Path) -> None:
        try:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
        except OSError:
            return
        self._checksums[str(path.relative_to(self.out_dir)).replace("\\", "/")] = digest

    def _referenced_responses(self) -> set[str]:
        refs: set[str] = set()
        for records in (self.posts.values(), self.users.values()):
            for record in records:
                origin = (record.get("provenance") if isinstance(record, dict)
                          else getattr(record, "provenance", None)) or {}
                if isinstance(origin, dict) and origin.get("response"):
                    refs.add(str(origin["response"]))
        for entry in self.media_index.values():
            if entry.get("discovered_from"):
                refs.add(str(entry["discovered_from"]))
        return refs

    def prune_unreferenced_responses(self) -> int:
        """Drop saved responses no kept record was read from.

        The signed-in client fetches the home feed, notifications and
        recommendations beside the target; those responses are in the WARC,
        which replays only with them, but the raw-response store is the
        evidence for kept records and keeps nothing else.
        """
        if not self.responses_dir.is_dir():
            return 0
        keep = self._referenced_responses()
        removed = 0
        for saved in sorted(self.responses_dir.glob("response-*.json")):
            ref = f"raw/responses/{saved.name}"
            if ref in keep:
                continue
            try:
                saved.unlink()
            except OSError:
                continue
            self._checksums.pop(ref, None)
            removed += 1
        self.responses_saved = len(list(self.responses_dir.glob("response-*.json")))
        return removed

    def finalise(self, manifest: dict, checkpoint: dict) -> None:
        _atomic_json(self.media_path, self.media_index)
        temporary = self.posts_path.with_name(self.posts_path.name + ".tmp")
        with temporary.open("w", encoding="utf-8") as handle:
            for post in self.posts.values():
                handle.write(json.dumps(self._post_row(post), ensure_ascii=False) + "\n")
        temporary.replace(self.posts_path)
        self._write_csv(self.out_dir / "x-posts.csv", self.POST_FIELDS,
                        (self._post_row(p) for p in self.posts.values()))
        _atomic_json(self.checkpoint_path, checkpoint)
        _atomic_json(self.manifest_path, manifest)
        for name in ("x-posts.jsonl", "x-posts.csv", "x-users.json",
                     "x-media.json", "x-manifest.json"):
            path = self.out_dir / name
            if path.exists():
                self._checksum(path)
        lines = [f"{digest}  {name}" for name, digest in sorted(self._checksums.items())]
        temporary = self.checksums_path.with_name("checksums.sha256.tmp")
        temporary.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
        temporary.replace(self.checksums_path)

    @staticmethod
    def _write_csv(path: Path, fields: list[str], rows: Iterable[dict]) -> None:
        temporary = path.with_name(path.name + ".tmp")
        with temporary.open("w", encoding="utf-8-sig", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
            writer.writeheader()
            for row in rows:
                current = dict(row)
                for key in ("media_urls", "media_files"):
                    if isinstance(current.get(key), list):
                        current[key] = json.dumps(current[key], ensure_ascii=False)
                writer.writerow(current)
        temporary.replace(path)


def _without_raw(row: dict) -> dict:
    row = dict(row)
    row.pop("raw", None)
    return row


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", str(value))[:120] or "item"


def _post_id_int(value: object) -> int:
    try:
        return int(str(value))
    except (TypeError, ValueError):
        return 0


# ---------------------------------------------------------------------------
# The capture itself
# ---------------------------------------------------------------------------

class XCaptureSession:
    """Runs one X job: several targets, one at a time.

    ``control_poll`` returns "pause", "resume", "stop" or None; the run
    checks it between posts and while waiting out a rate limit. ``on_progress``
    receives the state and a details dict for the dashboard. ``open_browser``
    is called with a URL when a person is needed and returns a closer.
    """

    def __init__(self, *, config: XCaptureConfig, client: XClient,
                 output_dir: Path, crawl_id: int, crawl_name: str,
                 known_ids: Optional[dict[str, set[str]]] = None,
                 control_poll: Optional[Callable[[], Optional[str]]] = None,
                 on_progress: Optional[Callable[..., None]] = None,
                 persist: Optional[Callable[..., None]] = None,
                 open_browser: Optional[Callable[[str], Callable[[], None]]] = None,
                 sleep: Callable[[float], None] = time.sleep):
        self.config = config
        self.client = client
        self.archive = XArchive(output_dir)
        self.crawl_id = crawl_id
        self.crawl_name = crawl_name
        self.known_ids = known_ids or {}
        self.control_poll = control_poll or (lambda: None)
        self.on_progress = on_progress or (lambda **_kw: None)
        self.persist = persist or (lambda **_kw: None)
        self.open_browser = open_browser
        self.sleep = sleep

        self.state = RECORDING
        self.phase_detail = "Starting."
        self.stop_reason: Optional[str] = None
        self.stop_rule: Optional[str] = None
        self.counters: Counter = Counter()
        self.exclusions: Counter = Counter()
        self.targets = [parse_x_target(u, config.search_product) for u in config.targets]
        self.target_status: dict[str, dict] = {
            t.key: {"label": t.label, "kind": t.kind, "status": "pending",
                    "posts_selected": 0, "posts_encountered": 0}
            for t in self.targets}
        self.target_ids: dict[str, str] = {}
        self._anomalies_drained = 0
        self.current_target: Optional[XTarget] = None
        self._stop_requested = False
        self._rate_limit_streak = 0
        self._last_report = 0.0
        self.viewer_id: Optional[str] = None
        self.newest_by_target: dict[str, dict] = {}
        self.absences: list[dict] = []

    # -- control ------------------------------------------------------------
    def _check_control(self) -> None:
        command = self.control_poll()
        if command == CMD_STOP:
            self._request_stop("curator_stop", "curator_selected_stop_and_save")
            return
        if command == CMD_PAUSE:
            self.state = PAUSED
            self.phase_detail = "Paused. Nothing further is requested from X until you resume."
            self.archive.event("paused", actor="dashboard")
            self._report(force=True)
            while True:
                self.sleep(1.0)
                command = self.control_poll()
                if command == CMD_STOP:
                    self._request_stop("curator_stop", "curator_selected_stop_and_save")
                    return
                if command == CMD_RESUME:
                    self.state = RECORDING
                    self.phase_detail = "Resumed."
                    self.archive.event("resumed", actor="dashboard")
                    self._report(force=True)
                    return

    def _request_stop(self, reason: str, rule: str) -> None:
        if not self._stop_requested:
            self._stop_requested = True
            self.stop_reason, self.stop_rule = reason, rule
            self.archive.event("stopping_rule_fired", reason=reason, rule=rule)

    def _hold_for_curator(self, why: str, url: str) -> bool:
        self.state = BLOCKED
        self.phase_detail = why
        self.archive.event("curator_needed", reason=why, url=url)
        self._report(force=True)
        close = None
        if self.open_browser is not None:
            try:
                close = self.open_browser(url)
            except Exception as exc:
                log.warning("Could not open the browser for the curator: %s", exc)
        try:
            while True:
                self.sleep(1.0)
                command = self.control_poll()
                if command == CMD_STOP:
                    self._request_stop("curator_stop", "curator_selected_stop_and_save")
                    return False
                if command == CMD_RESUME:
                    self.state = RECORDING
                    self.phase_detail = "Continuing."
                    self.archive.event("curator_resolved")
                    self._report(force=True)
                    return True
        finally:
            if close is not None:
                try:
                    close()
                except Exception:
                    pass

    def _wait_out_rate_limit(self, exc: RateLimited) -> bool:
        """Sit out a limit until the reset X named, still answering Stop."""
        self._rate_limit_streak += 1
        wait = float(exc.wait_seconds)
        if wait <= 0:
            wait = 60.0 * (2 ** (self._rate_limit_streak - 1))
        wait = max(20.0, min(wait, 960.0))
        self.counters["rate_limit_waits"] += 1
        self.archive.event("rate_limited", wait_seconds=wait,
                           streak=self._rate_limit_streak, detail=str(exc))
        remaining = wait
        while remaining > 0:
            self.phase_detail = (f"X is limiting requests. Waiting "
                                 f"{int(remaining)}s before continuing.")
            self._report(force=True)
            step = min(5.0, remaining)
            self.sleep(step)
            remaining -= step
            if self.control_poll() == CMD_STOP:
                self._request_stop("curator_stop", "curator_selected_stop_and_save")
                return False
        return True

    def _with_retries(self, action: Callable[[], object], url: str, what: str) -> object:
        for _attempt in range(6):
            if self._stop_requested:
                raise TargetUnavailable("stopped")
            try:
                result = action()
                self._rate_limit_streak = 0
                return result
            except RateLimited as exc:
                if not self._wait_out_rate_limit(exc):
                    raise TargetUnavailable("stopped") from exc
            except LoginRequired as exc:
                if not self._hold_for_curator(
                        f"X needs you to sign in before {what}: {exc}. Sign in "
                        "in the browser window that has opened, then select "
                        "\u201cI have resolved it \u2014 continue\u201d.", url):
                    raise TargetUnavailable("stopped") from exc
                self._refresh_client()
            except CheckpointRequired as exc:
                if not self._hold_for_curator(
                        f"X is asking for verification before {what}: {exc}. "
                        "Resolve it in the browser window that has opened, then "
                        "select \u201cI have resolved it \u2014 continue\u201d.", url):
                    raise TargetUnavailable("stopped") from exc
                self._refresh_client()
        raise TargetUnavailable(f"{what} did not succeed after repeated tries.")

    def _refresh_client(self) -> None:
        refresh = getattr(self.client, "refresh", None)
        if callable(refresh):
            try:
                refresh()
            except Exception as exc:
                log.warning("Session refresh failed: %s", exc)

    # -- progress -----------------------------------------------------------
    def _report(self, force: bool = False) -> None:
        now = time.monotonic()
        if not force and now - self._last_report < 1.0:
            return
        self._last_report = now
        try:
            self.on_progress(state=self.state,
                             visited=self._count_role("target"),
                             failed=self.counters.get("posts_failed", 0),
                             current_url=(self.current_target.url
                                          if self.current_target else None),
                             details=self._progress_details())
        except Exception as exc:
            log.debug("Progress report failed: %s", exc)

    def _rows(self) -> Iterator[dict]:
        for post in self.archive.posts.values():
            yield self.archive._post_row(post) if isinstance(post, XPost) else post

    def _count_role(self, role: str) -> int:
        return sum(1 for row in self._rows() if row.get("capture_role") == role)

    def _count_relationship(self, relationship: str) -> int:
        return sum(1 for row in self._rows()
                   if row.get("capture_role") == "target"
                   and row.get("relationship") == relationship)

    def _progress_details(self) -> dict:
        done = sum(1 for t in self.target_status.values()
                   if t["status"] in ("done", "failed", "unavailable"))
        dates = [row.get("created_time") for row in self._rows()
                 if row.get("capture_role") == "target" and row.get("created_time")]
        return {
            "phase": ("finished" if self.state == STOPPED
                      else "verification_required" if self.state == BLOCKED
                      else "collecting" if self.state == RECORDING
                      else "paused"),
            "message": self.phase_detail,
            "viewer": self.viewer_id or "signed_out",
            "targets_total": len(self.targets),
            "targets_done": done,
            "current_target": self.current_target.label if self.current_target else None,
            "posts_encountered": self.counters.get("posts_encountered", 0),
            "posts_exported": self._count_role("target"),
            "reposts_exported": self._count_relationship("repost"),
            "context_posts": self._count_role("conversation_context"),
            "replies_exported": self.counters.get("replies_collected", 0),
            # an account is a record of its own: a profile with no posts is
            # still captured, and its pages still open
            "users_exported": len(self.archive.users),
            "media_expected": self.counters.get("media_expected", 0),
            "media_captured": len(self.archive.media_index),
            "media_failed": self.counters.get("media_failed", 0),
            "newest_post": max(dates) if dates else None,
            "oldest_post": min(dates) if dates else None,
            "rate_limit_waits": self.counters.get("rate_limit_waits", 0),
            "warc_files": self.counters.get("warc_files") or len(
                list(self.archive.out_dir.glob("*.warc.gz"))),
            "targets": list(self.target_status.values()),
        }

    # -- the run --------------------------------------------------------------
    def run(self) -> dict:
        self.archive.event("capture_created", mode=self.config.mode,
                           targets=[t.url for t in self.targets],
                           continuation_of=self.config.continuation_of)
        record_responses = getattr(self.client, "record_responses_to", None)
        if callable(record_responses):
            record_responses(self.archive.save_response)
        attach_controls = getattr(self.client, "attach_engine_controls", None)
        if callable(attach_controls):
            attach_controls(self._check_control, lambda: self._stop_requested)
        if not self._establish_viewer():
            return self._finish()

        for target in self.targets:
            if self._stop_requested:
                break
            self.current_target = target
            status = self.target_status[target.key]
            status["status"] = "running"
            self.phase_detail = f"Collecting {target.label}."
            self._report(force=True)
            try:
                if target.kind == "profile":
                    self._capture_profile(target)
                elif target.kind == "post":
                    self._capture_single(target)
                else:
                    self._capture_search(target)
                if not self._stop_requested:
                    status["status"] = "done"
            except TargetUnavailable as exc:
                if str(exc) == "stopped":
                    status["status"] = "interrupted"
                    break
                status["status"] = "unavailable"
                status["reason"] = str(exc)
                self.counters["targets_unavailable"] += 1
                self.archive.event("target_unavailable", target=target.url, reason=str(exc))
            except XError as exc:
                status["status"] = "failed"
                status["reason"] = str(exc)
                self.counters["targets_failed"] += 1
                self.archive.event("target_failed", target=target.url, error=str(exc))
            finally:
                self._drain_client_anomalies()
                self._checkpoint()
        self.current_target = None
        if not self._stop_requested:
            self.stop_reason = self.stop_reason or "targets_complete"
            self.stop_rule = self.stop_rule or "every_target_worked"
        return self._finish()

    def _finish(self) -> dict:
        self.state = STOPPED
        self.phase_detail = self._closing_summary()
        self.archive.prune_unreferenced_responses()
        self.archive.finalise(self.manifest_document(final=True), self._checkpoint_document())
        self._report(force=True)
        try:
            self.persist(targets=self.newest_by_target, posts=list(self._rows()),
                         users=self.archive.users)
        except Exception as exc:
            log.warning("Could not persist capture state: %s", exc)
        return {"stop_reason": self.stop_reason, "stop_rule": self.stop_rule,
                "posts": self._count_role("target"),
                "context_posts": self._count_role("conversation_context"),
                "media": len(self.archive.media_index)}

    def _establish_viewer(self) -> bool:
        """A signed-in session is the product requirement.

        The browser opens for the curator on X's own sign-in page when the
        profile is not signed in. A curator who continues still signed out
        has decided; the run goes on and the manifest says what that bounds.
        """
        for attempt in range(3):
            try:
                self.viewer_id = self.client.viewer()
            except XError as exc:
                log.info("Viewer unknown: %s", exc)
                self.viewer_id = None
            if self.viewer_id:
                break
            still = " still" if attempt else ""
            held = self._hold_for_curator(
                f"The capture browser is{still} not signed in to X. Sign in in "
                "the window that has opened -- use a dedicated institutional "
                "account, not a personal one -- then select \u201cI have "
                "resolved it \u2014 continue\u201d. SWM reads the session from "
                "that browser profile; it never sees the password.",
                "https://x.com/i/flow/login")
            if not held:
                return False
            self._refresh_client()
            if attempt == 2:
                self.archive.event("proceeding_signed_out")
        self.archive.event("viewer", user_id=self.viewer_id, signed_in=bool(self.viewer_id))
        self._report(force=True)
        return True

    def _closing_summary(self) -> str:
        posts = self._count_role("target")
        context = self._count_role("conversation_context")
        media = len(self.archive.media_index)
        accounts = len(self.archive.users)
        because = {
            "targets_complete": "every target was worked",
            "curator_stop": "you selected Stop and save",
        }.get(self.stop_reason or "", str(self.stop_reason or "").replace("_", " "))
        return (f"Collected {accounts} account{'s' if accounts != 1 else ''}, "
                f"{posts} post{'s' if posts != 1 else ''}, "
                f"{context} context post{'s' if context != 1 else ''}, "
                f"{media} media file{'s' if media != 1 else ''}. "
                f"Stopped because {because}.")

    def _drain_client_anomalies(self) -> None:
        anomalies = getattr(self.client, "anomalies", None)
        if not isinstance(anomalies, list):
            return
        for anomaly in anomalies[self._anomalies_drained:]:
            if isinstance(anomaly, dict):
                self.archive.event("client_anomaly", **anomaly)
        self._anomalies_drained = len(anomalies)

    # -- a single post ----------------------------------------------------------
    def _capture_single(self, target: XTarget) -> None:
        post = self._with_retries(lambda: self.client.post(target.post_id or ""),
                                  target.url, f"reading {target.label}")
        assert isinstance(post, XPost)
        post.surface = "direct"
        post.capture_role = "target"
        self.counters["posts_encountered"] += 1
        self.target_status[target.key]["posts_encountered"] += 1
        if post.author_id:
            self.target_ids[target.key] = post.author_id
        self._take_post(post, target, conversation=True)

    # -- a profile --------------------------------------------------------------
    def _capture_profile(self, target: XTarget) -> None:
        handle = target.handle or ""
        user = self._with_retries(lambda: self.client.user(handle), target.url,
                                  f"reading {target.label}")
        assert isinstance(user, XUser)
        self.archive.add_user(user)
        self.target_ids[target.key] = user.user_id
        self.target_status[target.key]["user_id"] = user.user_id
        self.target_status[target.key]["handle"] = user.handle
        if user.is_protected and not self.viewer_id:
            raise TargetUnavailable(
                f"{target.label} is protected, and the capture browser is not "
                "signed in to an account that follows it.")
        if self.config.capture_media and user.profile_image_url:
            self._fetch_one(user.profile_image_url, f"profile image of {target.label}",
                            discovered_from=user.provenance.get("response"),
                            page_loaded_variant="as served", requested_variant="as served")
        seen: set[str] = set()
        for surface in self.config.surfaces:
            if self._stop_requested:
                return
            iterator = self.client.timeline(user, surface)
            try:
                self._walk_listing(target, surface, iterator, seen, user)
            finally:
                close = getattr(iterator, "close", None)
                if callable(close):
                    close()
            self._drain_client_anomalies()

    # -- a search ------------------------------------------------------------------
    def _capture_search(self, target: XTarget) -> None:
        iterator = self.client.search(target.query or "", target.product)
        try:
            self._walk_listing(target, "search", iterator, set(), None)
        finally:
            close = getattr(iterator, "close", None)
            if callable(close):
                close()

    def _is_targets_own(self, post: XPost, target: XTarget) -> bool:
        """The numeric id decides; the handle only where no id is known."""
        if target.kind != "profile":
            return True
        wanted_id = self.target_ids.get(target.key)
        if post.author_id and wanted_id:
            return str(post.author_id) == str(wanted_id)
        return (post.author_handle or "").lower() == (target.handle or "").lower()

    def _walk_listing(self, target: XTarget, surface: str, iterator: Iterator[XPost],
                      seen: set[str], user: Optional[XUser]) -> None:
        status = self.target_status[target.key]
        consecutive_older = 0
        prior = self.config.prior_newest.get(target.key) or {}
        pinned_ids = set(user.pinned_post_ids) if user else set()

        while True:
            if self._stop_requested:
                return
            try:
                post = self._with_retries(lambda: next(iterator), target.url,
                                          f"listing {target.label} {surface}")
            except TargetUnavailable:
                raise
            except StopIteration:
                break
            if not isinstance(post, XPost):
                break
            self._check_control()
            if self._stop_requested:
                return
            self.counters["posts_encountered"] += 1
            status["posts_encountered"] += 1
            if not self._is_targets_own(post, target):
                self.counters["foreign_posts_skipped"] += 1
                self.archive.event("foreign_post_skipped", target=target.label,
                                   post_id=post.post_id, author=post.author_handle)
                continue
            if post.post_id in pinned_ids:
                post.is_pinned = True
            post.surface = surface
            post.capture_role = "target"
            if post.post_id in seen:
                self.exclusions["duplicate_across_surfaces"] += 1
                continue
            seen.add(post.post_id)
            if post.relationship == "repost" and not self.config.keep_reposts:
                self.exclusions["reposts_not_requested"] += 1
                continue

            decision = self._decide(post, prior, target)
            if decision == "select":
                self._take_post(post, target, conversation=self.config.include_conversation)
                if not post.is_pinned:
                    consecutive_older = 0
            elif decision == "older":
                self.exclusions["older_than_requested"] += 1
                if not post.is_pinned:
                    consecutive_older += 1
            elif decision == "newer":
                self.exclusions["newer_than_requested"] += 1
            elif decision == "already_captured":
                self.exclusions["captured_previously"] += 1
                if not post.is_pinned:
                    consecutive_older += 1
            if self._boundary_reached(consecutive_older, self._selected_non_pinned(target)):
                return
        if status["posts_encountered"] == 0:
            self.archive.event("timeline_empty", target=target.url, surface=surface)
            status["empty_surfaces"] = sorted(set(status.get("empty_surfaces", [])) | {surface})
        if self.config.mode in ("until_stopped", "end_of_timeline"):
            self.archive.event("timeline_stalled", target=target.url, surface=surface,
                               posts_encountered=status["posts_encountered"])
            if self.config.mode == "end_of_timeline":
                self._request_stop("timeline_stalled", "no_unseen_posts_after_stall_rounds")

    def _decide(self, post: XPost, prior: dict, target: XTarget) -> str:
        mode = self.config.mode
        when = post.created_time or ""
        if mode == "date_range":
            if self.config.to_date and when and when > self.config.to_date:
                return "newer"
            if self.config.from_date and when and when < self.config.from_date:
                return "older"
            return "select"
        if mode == "latest_n":
            if post.is_pinned:
                return "select"
            # the count is the target's across its surfaces: the newest N
            # posts of the account, not N per tab
            return ("select" if self._selected_non_pinned(target) < self.config.latest_n
                    else "older")
        if mode == "since_last":
            # the pinned post sits first whatever its age; only a post
            # already captured is passed over, never one that is merely old
            if post.post_id in self.known_ids.get(target.key, set()):
                return "already_captured"
            if post.is_pinned:
                return "select"
            newest_id = _post_id_int(prior.get("post_id"))
            newest_date = str(prior.get("date") or "")
            if _post_id_int(post.post_id) and newest_id and _post_id_int(post.post_id) <= newest_id:
                return "already_captured"
            if newest_date and when and when <= newest_date:
                return "already_captured"
            return "select"
        return "select"

    def _selected_non_pinned(self, target: XTarget) -> int:
        status = self.target_status[target.key]
        return status["posts_selected"] - status.get("pinned_selected", 0)

    def _boundary_reached(self, consecutive_older: int, selected: int) -> bool:
        mode = self.config.mode
        if mode in ("date_range", "since_last"):
            if consecutive_older >= self.config.consecutive_older:
                self.archive.event("lower_boundary_reached", consecutive_older=consecutive_older)
                return True
        if mode == "latest_n" and selected >= self.config.latest_n:
            return True
        return False

    # -- one post's package -------------------------------------------------------
    def _take_post(self, post: XPost, target: XTarget, *, conversation: bool) -> None:
        post.provenance = {**post.provenance, "target_key": target.key}
        added = self.archive.add_post(post)
        if not added:
            return
        status = self.target_status[target.key]
        status["posts_selected"] += 1
        if post.is_pinned:
            status["pinned_selected"] = status.get("pinned_selected", 0) + 1
        self._track_newest(target, post)
        if self.config.capture_media:
            self._collect_media(post)
        self._collect_listing_context(post, target)
        if conversation and post.relationship != "repost":
            self._collect_conversation(post, target)
        self.phase_detail = (
            f"Collecting {target.label}: {self._count_role('target')} posts, "
            f"{len(self.archive.media_index)} media files"
            + (f", {self._count_role('conversation_context')} context posts"
               if conversation else "") + ".")
        self._report()
        if len(self.archive.posts) % 10 == 0:
            self._checkpoint()

    def _track_newest(self, target: XTarget, post: XPost) -> None:
        if post.is_pinned or target.kind == "post":
            return
        current = self.newest_by_target.get(target.key) or {}
        if not current or _post_id_int(post.post_id) > _post_id_int(current.get("post_id")):
            self.newest_by_target[target.key] = {
                "post_id": post.post_id, "date": post.created_time,
                "handle": target.handle, "user_id": self.target_ids.get(target.key),
                "url": target.url}

    def _collect_listing_context(self, post: XPost, target: XTarget) -> None:
        """Other people's posts the listing showed beside this one (a
        thread module on the Replies tab) are context, kept as such."""
        neighbours = getattr(self.client, "conversation_context", None)
        if not callable(neighbours) or not post.conversation_id:
            return
        try:
            found = neighbours(post.post_id)
        except Exception as exc:
            log.debug("Context lookup failed: %s", exc)
            return
        for other in found or []:
            if not isinstance(other, XPost) or other.post_id == post.post_id:
                continue
            if self._is_targets_own(other, target) and target.kind == "profile":
                continue          # the account's own posts are listed on their own
            other.capture_role = "conversation_context"
            other.surface = post.surface
            other.provenance = {**other.provenance, "target_key": target.key,
                                "context_for": post.post_id}
            if self.archive.add_post(other):
                self.counters["context_posts"] += 1
                if self.config.capture_media:
                    self._collect_media(other)

    def _media_of(self, post: XPost) -> list[tuple[XMediaItem, str]]:
        items = [(m, "post") for m in post.media]
        for kind, embedded in (("original_post", post.original_post),
                               ("quoted_post", post.quoted_post)):
            for entry in (embedded or {}).get("media") or []:
                if isinstance(entry, dict) and entry.get("url"):
                    already = any(m.url == entry["url"] for m, _ in items)
                    if not already:
                        items.append((XMediaItem(
                            url=str(entry["url"]), kind=str(entry.get("kind") or "image"),
                            position=int(entry.get("position") or 0),
                            page_url=entry.get("page_url"),
                            requested_variant=str(entry.get("requested_variant") or "orig")),
                            kind))
        return items

    def _collect_media(self, post: XPost) -> None:
        for item, part in self._media_of(post):
            self.counters["media_expected"] += 1
            if item.url in self.archive.media_index:
                continue
            self._fetch_one(item.url, f"downloading media for {post.post_id}",
                            discovered_from=post.provenance.get("response"),
                            page_loaded_variant=item.page_url,
                            requested_variant=item.requested_variant,
                            fallbacks=list(item.fallback_urls), post_id=post.post_id,
                            part=part)

    def _fetch_one(self, url: str, what: str, *, discovered_from: Optional[str],
                   page_loaded_variant: Optional[str], requested_variant: Optional[str],
                   fallbacks: Optional[list[str]] = None, post_id: Optional[str] = None,
                   part: str = "post") -> Optional[dict]:
        candidates = [url] + [f for f in (fallbacks or []) if f != url]
        last_error = "empty response"
        for candidate in candidates:
            try:
                body, content_type = self._with_retries(
                    lambda: self.client.fetch(candidate), candidate, what)
            except TargetUnavailable as exc:
                if str(exc) == "stopped":
                    return None
                last_error = str(exc)
                continue
            except XError as exc:
                last_error = str(exc)
                continue
            if not body:
                continue
            variant = requested_variant
            if candidate != url:
                variant = f"{requested_variant} refused; fell back to {candidate}"
                self.archive.event("media_fallback", post_id=post_id, requested=url,
                                   served=candidate)
            return self.archive.save_media(
                url, body, content_type, discovered_from=discovered_from,
                page_loaded_variant=page_loaded_variant, requested_variant=variant,
                fetched_url=candidate,
                fetched_via=getattr(self.client, "last_fetch_via", None))
        self.counters["media_failed"] += 1
        self.archive.event("media_failed", post_id=post_id, url=url, part=part,
                           error=last_error)
        return None

    def _collect_conversation(self, post: XPost, target: XTarget) -> None:
        """The post's page: what it replies to, and the replies under it.

        Replies are posts with their own ids and authors, kept as context
        (they are not the account's), up to the cap; the ancestors the post
        replies to are context too. The outcome is graded per post the way
        the Instagram mode grades comments.
        """
        wanted = self.config.max_replies_per_post
        replies = 0
        stop_reason = "exhausted"
        try:
            iterator = self._with_retries(
                lambda: self.client.conversation(post.post_id), post.permalink_url or "",
                f"reading the conversation of {post.post_id}")
            for other in iterator:      # type: ignore[union-attr]
                if self._stop_requested:
                    stop_reason = "stopped"
                    return
                if not isinstance(other, XPost) or other.post_id == post.post_id:
                    continue
                # a direct reply, or -- when the post is its conversation's
                # root -- anything later in that conversation
                is_reply = (other.in_reply_to_post_id == post.post_id or
                            (post.conversation_id == post.post_id
                             and other.conversation_id == post.post_id
                             and _post_id_int(other.post_id) > _post_id_int(post.post_id)))
                if is_reply:
                    if replies >= wanted:
                        self.exclusions["reply_limit_reached"] += 1
                        stop_reason = "reply_limit_reached"
                        break
                    replies += 1
                other.capture_role = "conversation_context"
                other.surface = "conversation"
                other.provenance = {**other.provenance, "target_key": target.key,
                                    "context_for": post.post_id}
                if self.archive.add_post(other):
                    self.counters["context_posts"] += 1
                    if is_reply:
                        self.counters["replies_collected"] += 1
                    if self.config.capture_media:
                        self._collect_media(other)
        except TargetUnavailable as exc:
            if str(exc) == "stopped":
                stop_reason = "stopped"
                return
            stop_reason = "failed"
            self.counters["conversations_failed"] += 1
            self.archive.event("conversation_failed", post_id=post.post_id, error=str(exc))
        except XError as exc:
            stop_reason = "failed"
            self.counters["conversations_failed"] += 1
            self.archive.event("conversation_failed", post_id=post.post_id, error=str(exc))
        finally:
            self._note_absences(post)
            self._grade_conversation(post, replies, stop_reason)

    def _note_absences(self, post: XPost) -> None:
        absences = getattr(self.client, "absences", None)
        if not callable(absences):
            return
        try:
            found = absences(post.post_id)
        except Exception:
            return
        for absence in found or []:
            if isinstance(absence, XAbsence):
                record = {"conversation_of": post.post_id, "kind": absence.kind,
                          "reason": absence.reason, "post_id": absence.post_id,
                          "entry_id": absence.entry_id}
                self.absences.append(record)
                self.archive.event("post_unavailable", **record)

    def _grade_conversation(self, post: XPost, observed: int, stop_reason: str) -> None:
        reported = post.reply_count if isinstance(post.reply_count, int) else None
        more_pages = getattr(self.client, "conversation_more", lambda: None)()
        if stop_reason == "stopped":
            status = "stopped_by_curator"
        elif stop_reason == "failed":
            status = "partial"
        elif reported == 0 and observed == 0:
            status = "no_replies_reported"
        elif stop_reason == "reply_limit_reached":
            status = "capped"
        elif reported is not None and observed >= reported:
            # X's conversation page always offers a cursor; a count that is
            # reached is reached whatever the page still offers
            status = "reported_count_reached"
        elif more_pages is True or reported is not None:
            status = "partial"
        else:
            status = "exhausted_unverified"
        post.reply_capture = {
            "status": status, "observed": observed, "reported": reported,
            "more_pages_seen": more_pages, "stop_reason": stop_reason,
            "cap": self.config.max_replies_per_post,
        }
        self.counters[f"replies_{status}"] += 1

    def _reply_statuses(self) -> dict:
        statuses: Counter = Counter()
        for row in self._rows():
            capture = row.get("reply_capture") or {}
            if capture.get("status"):
                statuses[capture["status"]] += 1
        return dict(statuses)

    # -- checkpoint and manifest ------------------------------------------------
    def _checkpoint(self) -> None:
        try:
            _atomic_json(self.archive.checkpoint_path, self._checkpoint_document())
        except OSError as exc:
            log.warning("Checkpoint failed: %s", exc)

    def _checkpoint_document(self) -> dict:
        return {
            "schema": "swm-x-checkpoint-v1",
            "updated_at": _iso_now(),
            "crawl_id": self.crawl_id,
            "mode": self.config.mode,
            "targets": list(self.target_status.values()),
            "newest_by_target": self.newest_by_target,
            "phase": self._progress_details()["phase"],
            "message": self.phase_detail,
            "posts_exported": self._count_role("target"),
            "context_posts": self._count_role("conversation_context"),
            "users_exported": len(self.archive.users),
            "media_captured": len(self.archive.media_index),
            "stop_reason": self.stop_reason,
            "stop_rule": self.stop_rule,
        }

    def manifest_document(self, *, final: bool = False) -> dict:
        details = self._progress_details()
        from .metadata import manifest_section
        operations = getattr(self.client, "operations_observed", None)
        searches = [t for t in self.targets if t.kind == "search"]
        return {
            "schema": "swm-x-capture-manifest-v1",
            "metadata": manifest_section(self.archive.out_dir),
            "capture": {
                "crawl_id": self.crawl_id,
                "name": self.crawl_name,
                "operator": self.config.operator,
                "client": getattr(self.client, "version", None),
                "targets": [{"url": t.url, "kind": t.kind, **self.target_status[t.key]}
                            for t in self.targets],
                "mode": self.config.mode,
                "parameters": {
                    "from": self.config.from_date, "to": self.config.to_date,
                    "latest_n": self.config.latest_n,
                    "consecutive_older_required": self.config.consecutive_older,
                    "surfaces": list(self.config.surfaces),
                    "search_product": self.config.search_product,
                    "capture_media": self.config.capture_media,
                    "keep_reposts": self.config.keep_reposts,
                    "include_conversation": self.config.include_conversation,
                    "maximum_replies_per_post": self.config.max_replies_per_post,
                    "write_warc": self.config.write_warc,
                },
                "viewer": "signed_in" if self.viewer_id else "signed_out",
                "continuation_of": self.config.continuation_of,
                "state": self.state,
                "final": final,
                "stop_reason": self.stop_reason,
                "stopping_rule_fired": self.stop_rule,
            },
            "layers": {
                "media": {
                    "path": "media/",
                    "meaning": "Images are the orig rendition as served by X for "
                               "a name=orig request SWM made (the page loaded a "
                               "sized rendition; both are recorded per file). "
                               "Videos and GIFs are the highest-bitrate "
                               "progressive MP4 variant X advertised, not shown "
                               "to be the upload. Content-addressed by SHA-256.",
                },
                "raw": {
                    "path": "raw/",
                    "responses": "raw/responses/",
                    "responses_saved": self.archive.responses_saved,
                    "meaning": "X's own responses as the browser received them, "
                               "with the browser session's own material removed. "
                               "Only responses a kept record or media file was "
                               "read from are retained; every record's provenance "
                               "names its response, the operation, the entry id "
                               "and the instruction it sat in.",
                },
                "normalised": {
                    "posts": ["x-posts.jsonl", "x-posts.csv"],
                    "users": "x-users.json",
                    "record_model": {
                        "record_type": "post",
                        "relationship": "original | reply | repost | quote",
                        "capture_role": "target | conversation_context",
                        "reposts": "kept as the account's timeline entries; the "
                                   "original post and its author are under "
                                   "original_post, and the account is never the "
                                   "author of the original",
                        "quotes": "the quoting account's post with the quoted post "
                                  "under quoted_post",
                        "context": "other people's posts pulled in to explain a "
                                   "conversation; never counted as the account's",
                    },
                    "selection_exclusions": dict(self.exclusions),
                },
                "web_context": {
                    "warc": "*.warc.gz" if (self.counters.get("warc_files")
                                            or any(self.archive.out_dir.glob("*.warc.gz")))
                    else None,
                    "meaning": "Optional record of every exchange the browser "
                               "made, for how X presented what was collected. "
                               "A replay aid and the record of presentation; the "
                               "raw responses are the evidence and the normalised "
                               "records with media and fixity the durable record.",
                },
                "fixity": "checksums.sha256",
            },
            "operations_observed": dict(operations) if isinstance(operations, dict) else None,
            "counts": dict(self.counters) | {
                "reply_statuses": self._reply_statuses(),
                "warc_files": self.counters.get("warc_files") or len(
                    list(self.archive.out_dir.glob("*.warc.gz"))),
                "posts_exported": self._count_role("target"),
                "users_exported": len(self.archive.users),
                "authored_posts": (self._count_relationship("original")
                                   + self._count_relationship("reply")
                                   + self._count_relationship("quote")),
                "reposts": self._count_relationship("repost"),
                "quotes": self._count_relationship("quote"),
                "replies_by_target": self._count_relationship("reply"),
                "context_posts": self._count_role("conversation_context"),
                "posts_unavailable": len(self.absences),
                "media_captured": len(self.archive.media_index),
                "targets_total": len(self.targets),
                "targets_done": details["targets_done"],
            },
            "coverage": {
                "newest_post": details["newest_post"],
                "oldest_post": details["oldest_post"],
                "absences": self.absences[:200],
            },
            "completeness": {
                "claim": "This package holds what X served this signed-in session "
                         "for these targets during this capture. It does not "
                         "claim to hold everything X holds.",
                "timeline_end": "A timeline is walked until no unseen post appears "
                                "across the stall rounds; that is reported as "
                                "timeline_stalled and "
                                "available_timeline_exhausted_unverified, never "
                                "as the end of the account's posts.",
                "search_meaning": ("A search or hashtag capture is what X served "
                                   "this account for this query, in this product "
                                   "tab, at this time. X ranks and personalises "
                                   "results; the query and product are the "
                                   "provenance.") if searches else None,
                "signed_out_capture_meaning": (
                    "Signed out, X serves little or nothing of a profile. What is "
                    "here is bounded by that, not by the request.")
                if not self.viewer_id else None,
                "engagement_figures": "Reply, repost, like, quote, bookmark and "
                                      "view counts are observations at capture time.",
                "pinned_detection": "A pinned post is the one X's TimelinePinEntry "
                                    "instruction names, cross-checked against the "
                                    "user's pinned_tweet_ids_str; it never ends a "
                                    "date-bounded capture on its own.",
            },
            "tools": {"swm_x": "1", "client": getattr(self.client, "version", "unknown")},
            "updated_at": _iso_now(),
        }
